name = "All the Mods 9"
author = "ATMTeam"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9719001d4d0fa38e3561cadd2b27eebf8e596b65a0490c49b0a79ce30af1dcf5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
