name = "All the Mods 9"
author = "ATMTeam"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7951b36ae823c36609b74ad942f50c6474e5e75b7389f109dc38faae769ccac2"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
